import { globals } from './globals.js';
import './input-keyboard.js';
import './input-mouse.js';
// TODO: Import this after you finish it
// import './input-gamepad.js';

// TODO: There are a lot of duplicates. Maybe we can consolidate if we're smart

const Inputs = {
    'ALL': [],
    'EDITOR': [],
    'MULTIPLAYER': [],
    'MULTIPLAYERHOST': [],
    'GAME': [],
};
Inputs.ALL = [
    {
        description: 'Toggle the main menu',
        event_id: 'toggle_main_menu',
        code: 'KeyX',
        friendlyCode: 'X',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: 9,
    },
    { 
        description: 'Toggle the cheatsheet',
        event_id: 'toggle_cheatsheet',
        code: 'KeyH',
        friendlyCode: 'H',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: 8,
    },
];

Inputs.EDITOR = [
    {
        description: 'Clickable View Selected',
        event_id: 'clickable_view_selected',
        // TODO: keyboard combo here so you can change the clicked editor portion you want to deal with
    },
    {
        description: 'Toggle Editor',
        event_id: 'toggle_editor',
        code: 'KeyP',
        friendlyCode: 'P',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Toggle Atlas',
        event_id: 'toggle_atlas',
        code: 'KeyA',
        friendlyCode: 'A',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Toggle Entity Editor',
        event_id: 'toggle_entity_editor',
        code: 'KeyE',
        friendlyCode: 'E',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Change Layer',
        event_id: 'change_layer',
        code: 'KeyL',
        friendlyCode: 'L',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Add Collision',
        event_id: 'add_collision',
        code: 'KeyA',
        friendlyCode: 'SHIFT+A',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Delete Collision',
        event_id: 'delete_collision',
        code: 'KeyD',
        friendlyCode: 'SHIFT+D',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Apply Current Data To Layer',
        event_id: 'apply_current_data_to_layer',
        code: 'KeyV',
        friendlyCode: 'V',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Apply Zero Data To Layer',
        event_id: 'apply_zero_data_to_layer',
        code: 'KeyZ',
        friendlyCode: 'Z',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Extract Data From Selected Coord',
        event_id: 'extract_data_from_selected_coord',
        code: 'KeyX',
        friendlyCode: 'SHIFT+X',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Extract Image From Data',
        event_id: 'extract_image_from_data',
        code: 'KeyI',
        friendlyCode: 'I',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
];

Inputs.MULTIPLAYER = [
    // {
    //     description: 'Toggle Leaderboard',
    //     context: globals.MODES.indexOf('MULTIPLAYER'),
    //     code: 'Digit1',
    //     friendlyCode: 'Shift+1',
    //     shiftKey: true,
    //     ctrlKey: false,
    //     callback: () => {
    //         this.toggleLeaderboardDisplay();
    //     }
    // },
    // TODO: Need to also map to Numpad2,3 etc...
    {
        description: 'Toggle On-Screen Controls',
        event_id: 'toggle_on_screen_controls',
        code: 'Digit2',
        friendlyCode: 'Shift+2',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Toggle Player List',
        event_id: 'toggle_player_list',
        code: 'Digit3',
        friendlyCode: 'Shift+3',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Spawn',
        event_id: 'spawn',
        code: 'KeyS',
        friendlyCode: 'Shift+S',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Despawn',
        event_id: 'despawn',
        code: 'KeyD',
        friendlyCode: 'Shift+D',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Up',
        event_id: 'move_up',
        code: 'KeyI',
        friendlyCode: 'I',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Down',
        event_id: 'move_down',
        code: 'KeyK',
        friendlyCode: 'K',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Right',
        event_id: 'move_right',
        code: 'KeyL',
        friendlyCode: 'L',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Left',
        event_id: 'move_left',
        code: 'KeyJ',
        friendlyCode: 'J',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Attack',
        event_id: 'attack',
        code: 'Space',
        friendlyCode: 'Space',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera up',
        event_id: 'move_camera_up',
        code: 'ArrowUp',
        friendlyCode: '↑',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera down',
        event_id: 'move_camera_down',
        code: 'ArrowDown',
        friendlyCode: '↓',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera left',
        event_id: 'move_camera_left',
        code: 'ArrowLeft',
        friendlyCode: '←',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera right',
        event_id: 'move_camera_right',
        code: 'ArrowRight',
        friendlyCode: '→',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
];

Inputs.MULTIPLAYERHOST = [
    {
        description: 'Toggle Leaderboard',
        event_id: 'toggle_leaderboard',
        code: 'Digit1',
        friendlyCode: 'Shift+1',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Toggle Host Controls',
        event_id: 'toggle_host_controls',
        code: 'Digit2',
        friendlyCode: 'Shift+2',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Toggle Player List',
        event_id: 'toggle_player_list',
        code: 'Digit3',
        friendlyCode: 'Shift+3',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera up',
        event_id: 'move_camera_up',
        code: 'ArrowUp',
        friendlyCode: '↑',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera down',
        event_id: 'move_camera_down',
        code: 'ArrowDown',
        friendlyCode: '↓',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera left',
        event_id: 'move_camera_left',
        code: 'ArrowLeft',
        friendlyCode: '←',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera right',
        event_id: 'move_camera_right',
        code: 'ArrowRight',
        friendlyCode: '→',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
];

Inputs.GAME = [
    {
        description: 'Toggle the main menu',
        event_id: 'toggle_main_menu',
        code: 'KeyX',
        friendlyCode: 'X',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera up',
        event_id: 'move_camera_up',
        code: 'ArrowUp',
        friendlyCode: '↑',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera down',
        event_id: 'move_camera_down',
        code: 'ArrowDown',
        friendlyCode: '↓',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera left',
        event_id: 'move_camera_left',
        code: 'ArrowLeft',
        friendlyCode: '←',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move camera right',
        event_id: 'move_camera_right',
        code: 'ArrowRight',
        friendlyCode: '→',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Change Modes',
        event_id: 'change_modes',
        code: 'KeyM',
        friendlyCode: 'SHIFT+M',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Up',
        event_id: 'move_up',
        code: 'KeyI',
        friendlyCode: 'I',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Down',
        event_id: 'move_down',
        code: 'KeyK',
        friendlyCode: 'K',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Left',
        event_id: 'move_left',
        code: 'KeyJ',
        friendlyCode: 'J',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Move Right',
        event_id: 'move_right',
        code: 'KeyL',
        friendlyCode: 'L',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Attack',
        event_id: 'attack',
        code: 'Space',
        friendlyCode: 'Space',
        shiftKey: false,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Connect to multiplayer',
        event_id: 'connect_to_multiplayer',
        code: 'Digit7',
        friendlyCode: 'Shift+7',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    },
    {
        description: 'Connect to multiplayer (as host)',
        event_id: 'connect_to_multiplayer_as_host',
        code: 'Digit8',
        friendlyCode: 'Shift+8',
        shiftKey: true,
        ctrlKey: false,
        gamepadButton: null,
    }
];

export { Inputs };
