export const _WASM_IMPORTS = {
    debug_getData(index) {},
    debug_addData(value) {},
    debug_getLength() {},
    debug_clearAll() {},
    debug_testPanic() {},
    debug_testBreakpoint() {},
    debug_testTrap() {},
    diff_getData(index) {},
    diff_getLength() {},
    diff_addData(data) {},
    diff_clearAll() {},
    editor_createLayer(width, height, layer_type) {},
    editor_attachLayerToWorld(world_index, layer_index) {},
    editor_createWorld(width, height) {},
    editor_totalWorlds() {},
    editor_totalLayers() {},
    editor_totalEntities() {},
    editor_createEntity(entity_type) {},
    editor_getEntityType(entity) {},
    editor_clearWorlds() {},
    editor_clearEntities() {},
    editor_clearAll() {},
    editor_modifyWorldData(world, layer, x, y, new_value) {},
    editor_resizeWorld(world, width, height) {},
    editor_addRowToWorld(world) {},
    editor_addColumnToWorld(world) {},
    editor_removeRowFromWorld(world) {},
    editor_removeColumnFromWorld(world) {},
    editor_addLayerToWorld(world) {},
    editor_injectLayerToWorldAfter(world, layer_index) {},
    editor_getWorldMemoryLocation(world) {},
    editor_getWorldMemoryLength(world) {},
    editor_getEntityMemoryLocation(entity) {},
    editor_getEntityMemoryLength(entity) {},
    inputs_inputUp(entity) {},
    inputs_inputDown(entity) {},
    inputs_inputLeft(entity) {},
    inputs_inputRight(entity) {},
    game_entityIncrementHealth(entity) {},
    game_entityDecrementHealth(entity) {},
    game_entityAttack(entity, target, crit_buff) {},
    game_entityGetHealth(entity) {},
    game_entityGetWorldX(entity) {},
    game_entityGetWorldY(entity) {},
    game_entityGetType(entity) {},
    game_entitySetHealth(entity, value) {},
    game_initializeGame() {},
    game_loadWorld(index) {},
    game_getCurrentWorldIndex() {},
    game_getCurrentWorldWidth() {},
    game_getCurrentWorldHeight() {},
    game_readFromEmbeddedFile(file_index, index, mode) {},
    game_getWorldData(world, layer, x, y) {},
    game_setWorldData(world, layer, x, y, value) {},
    game_getWorldAtViewport(layer, x, y) {},
    game_translateViewportXToWorldX(x) {},
    game_translateViewportYToWorldY(y) {},
    renderer_getPositionX() {},
    renderer_getPositionY() {},
    renderer_setPosition(x, y) {},
    viewport_setSize(width, height) {},
    viewport_initializeViewportData() {},
    viewport_setData(x, y, value) {},
    viewport_getData(x, y) {},
    viewport_getDataByIndex(index) {},
    viewport_getSizeWidth() {},
    viewport_getSizeHeight() {},
    viewport_setPaddingTop(value) {},
    viewport_setPaddingBottom(value) {},
    viewport_setPaddingLeft(value) {},
    viewport_setPaddingRight(value) {},
    viewport_getPaddingTop() {},
    viewport_getPaddingBottom() {},
    viewport_getPaddingLeft() {},
    viewport_getPaddingRight() {},
    viewport_getXFromIndex(index) {},
    viewport_getYFromIndex(index) {},
    viewport_getLength() {},
    viewport_clear() {},
};
