var GAME_GOODS = [
  {"name": "Clove"},
  {"name": "Cinnamon"},
  {"name": "Pepper"},
  {"name": "Nutmeg"},
  {"name": "Pimento"},
  {"name": "Ginger"},
  {"name": "Vanilla"},
  {"name": "Tea"},
  {"name": "Coffee"},
  {"name": "Cacao"},
  {"name": "Sugar"},
  {"name": "Cheese"},
  {"name": "Fish"},
  {"name": "Grain"},
  {"name": "Olive Oil"},
  {"name": "Raisins"},
  {"name": "Rock Salt"},
  {"name": "Silk"},
  {"name": "Cotton"},
  {"name": "Wool"},
  {"name": "Flax"},
  {"name": "Cotton Cloth"},
  {"name": "Silk Cloth"},
  {"name": "Wool Cloth"},
  {"name": "Velvet"},
  {"name": "Linen Cloth"},
  {"name": "Coral"},
  {"name": "Amber"},
  {"name": "Ivory"},
  {"name": "Pearl"},
  {"name": "Tortoise Shell"},
  {"name": "Gold"},
  {"name": "Silver"},
  {"name": "Copper Ore"},
  {"name": "Tin Ore"},
  {"name": "Iron Ore"},
  {"name": "Art"},
  {"name": "Carpet"},
  {"name": "Musk"},
  {"name": "Perfume"},
  {"name": "Glass Beads"},
  {"name": "Dye"},
  {"name": "Porcelain"},
  {"name": "Glassware"},
  {"name": "Arms"},
  {"name": "Wood"}
];
