var GAME_PORTS = [
  {"name": "Abidjan", "location": "W. Africa", "specialty": "Musk"},
  {"name": "Aden", "location": "Arabia", "specialty": "Amber"},
  {"name": "Alexandria", "location": "Ottoman", "specialty": "Cotton Cloth"},
  {"name": "Algiers", "location": "N. Africa", "specialty": null},
  {"name": "Amboa", "location": "S. Asia", "specialty": "Nutmeg"},
  {"name": "Amsterdam", "location": "N. Europe", "specialty": "Glass Beads"},
  {"name": "Antwerp", "location": "N. Europe", "specialty": "Wool Cloth"},
  {"name": "Argin", "location": "W. Africa", "specialty": null},
  {"name": "Athens", "location": "Mediterranean", "specialty": "Art"},
  {"name": "Azov", "location": "Ottoman", "specialty": null},
  {"name": "Banda", "location": "S. Asia", "specialty": "Nutmeg"},
  {"name": "Bankao", "location": "S. Asia", "specialty": null},
  {"name": "Barcelona", "location": "Iberia", "specialty": "Rock Salt"},
  {"name": "Basra", "location": "Arabia", "specialty": "Cheese"},
  {"name": "Bathurst", "location": "W. Africa", "specialty": null},
  {"name": "Beirut", "location": "Ottoman", "specialty": "Carpet"},
  {"name": "Belgrade", "location": "Ottoman", "specialty": null},
  {"name": "Bergen", "location": "N. Europe", "specialty": null},
  {"name": "Bissau", "location": "W. Africa", "specialty": null},
  {"name": "Bordeaux", "location": "N. Europe", "specialty": "Raisins"},
  {"name": "Bristol", "location": "N. Europe", "specialty": "Tin Ore"},
  {"name": "Cairo", "location": "Arabia", "specialty": "Art"},
  {"name": "Calicut", "location": "India", "specialty": "Nutmeg"},
  {"name": "Callao", "location": "S. America", "specialty": null},
  {"name": "Candia", "location": "Mediterranean", "specialty": null},
  {"name": "Cape Cod", "location": "Arctic", "specialty": null},
  {"name": "Cape Town", "location": "W. Africa", "specialty": null},
  {"name": "Caracas", "location": "S. America", "specialty": "Vanilla"},
  {"name": "Cartegena", "location": "S. America", "specialty": null},
  {"name": "Cayenne", "location": "S. America", "specialty": "Wood"},
  {"name": "Ceuta", "location": "N. Africa", "specialty": null},
  {"name": "Ceylon", "location": "India", "specialty": "Cinnamon"},
  {"name": "Changan", "location": "E. Asia", "specialty": "Silk Cloth"},
  {"name": "Churchill", "location": "Arctic", "specialty": null},
  {"name": "Cochin", "location": "India", "specialty": null},
  {"name": "Copenhagen", "location": "N. Europe", "specialty": "Glassware"},
  {"name": "Coppermine", "location": "Arctic", "specialty": null},
  {"name": "Danzig", "location": "N. Europe", "specialty": null},
  {"name": "Dikson", "location": "Russia", "specialty": null},
  {"name": "Dili", "location": "S. Asia", "specialty": "Clove"},
  {"name": "Diu", "location": "India", "specialty": null},
  {"name": "Dublin", "location": "N. Europe", "specialty": null},
  {"name": "Ezo", "location": "E. Asia", "specialty": null},
  {"name": "Forel", "location": "Arctic", "specialty": null},
  {"name": "Geelong", "location": "Australia", "specialty": null},
  {"name": "Genoa", "location": "Mediterranean", "specialty": "Silver"},
  {"name": "Goa", "location": "India", "specialty": "Ginger"},
  {"name": "Guam", "location": "E. Asia", "specialty": null},
  {"name": "Guatemala", "location": "C. America", "specialty": "Grain"},
  {"name": "Hamburg", "location": "N. Europe", "specialty": "Dye"},
  {"name": "Hanoi", "location": "E. Asia", "specialty": "Coral"},
  {"name": "Havana", "location": "C. America", "specialty": "Vanilla"},
  {"name": "Hekla", "location": "N. Europe", "specialty": null},
  {"name": "Hormuz", "location": "Arabia", "specialty": "Ginger"},
  {"name": "Istanbul", "location": "Ottoman", "specialty": "Carpet"},
  {"name": "Jaffa", "location": "Ottoman", "specialty": null},
  {"name": "Jamaica", "location": "C. America", "specialty": "Sugar"},
  {"name": "Juneau", "location": "Arctic", "specialty": null},
  {"name": "Kaffa", "location": "Ottoman", "specialty": "Iron Ore"},
  {"name": "Korf", "location": "Russia", "specialty": null},
  {"name": "Leveque", "location": "Australia", "specialty": null},
  {"name": "Lisbon", "location": "Iberia", "specialty": "Rock Salt"},
  {"name": "London", "location": "N. Europe", "specialty": "Wool"},
  {"name": "Luanda", "location": "W. Africa", "specialty": "Coral"},
  {"name": "Lubeck", "location": "N. Europe", "specialty": "Silver"},
  {"name": "Lushun", "location": "E. Asia", "specialty": null},
  {"name": "Macao", "location": "E. Asia", "specialty": null},
  {"name": "Madeira", "location": "W. Africa", "specialty": "Sugar"},
  {"name": "Malacca", "location": "S. Asia", "specialty": "Cinnamon"},
  {"name": "Malindi", "location": "E. Africa", "specialty": "Musk"},
  {"name": "Maracaibo", "location": "S. America", "specialty": null},
  {"name": "Margarita", "location": "S. America", "specialty": null},
  {"name": "Marseille", "location": "Mediterranean", "specialty": "Perfume"},
  {"name": "Massawa", "location": "Arabia", "specialty": "Pimento"},
  {"name": "Mecca", "location": "Arabia", "specialty": "Musk"},
  {"name": "Mindanao", "location": "S. Asia", "specialty": null},
  {"name": "Mogadishu", "location": "E. Africa", "specialty": "Ivory"},
  {"name": "Mollendo", "location": "S. America", "specialty": null},
  {"name": "Mombasa", "location": "E. Africa", "specialty": null},
  {"name": "Montevideo", "location": "S. America", "specialty": null},
  {"name": "Moresby", "location": "S. Asia", "specialty": null},
  {"name": "Mozambique", "location": "E. Africa", "specialty": null},
  {"name": "Muscat", "location": "Arabia", "specialty": null},
  {"name": "Naalehu", "location": "Arctic", "specialty": null},
  {"name": "Nagasaki", "location": "E. Asia", "specialty": "Silver"},
  {"name": "Nantes", "location": "N. Europe", "specialty": null},
  {"name": "Naples", "location": "Mediterranean", "specialty": "Wool Cloth"},
  {"name": "Narvik", "location": "N. Europe", "specialty": null},
  {"name": "Nicosia", "location": "Mediterranean", "specialty": "Copper Ore"},
  {"name": "Nome", "location": "Arctic", "specialty": null},
  {"name": "Oslo", "location": "N. Europe", "specialty": "Wood"},
  {"name": "Palma", "location": "Mediterranean", "specialty": null},
  {"name": "Panama", "location": "C. America", "specialty": null},
  {"name": "Pasei", "location": "S. Asia", "specialty": null},
  {"name": "Pernambuco", "location": "S. America", "specialty": "Dye"},
  {"name": "Pisa", "location": "Mediterranean", "specialty": "Silk Cloth"},
  {"name": "Porto Velho", "location": "C. America", "specialty": null},
  {"name": "Quatar", "location": "Arabia", "specialty": "Tortoise Shell"},
  {"name": "Quelimane", "location": "E. Africa", "specialty": "Tortoise Shell"},
  {"name": "Ragusa", "location": "Mediterranean", "specialty": "Dye"},
  {"name": "Riga", "location": "N. Europe", "specialty": "Wood"},
  {"name": "Rio de Janeiro", "location": "S. America", "specialty": "Gold"},
  {"name": "Sakai", "location": "E. Asia", "specialty": "Silk Cloth"},
  {"name": "Salonika", "location": "Ottoman", "specialty": null},
  {"name": "San Jorge", "location": "W. Africa", "specialty": "Ivory"},
  {"name": "Santa Barbara", "location": "C. America", "specialty": null},
  {"name": "Santa Cruz", "location": "W. Africa", "specialty": null},
  {"name": "Santiago", "location": "C. America", "specialty": null},
  {"name": "Santo Domingo", "location": "C. America", "specialty": "Sugar"},
  {"name": "Seville", "location": "Iberia", "specialty": "Porcelain"},
  {"name": "Shiraz", "location": "Arabia", "specialty": null},
  {"name": "Sofala", "location": "E. Africa", "specialty": "Ivory"},
  {"name": "Stockholm", "location": "N. Europe", "specialty": "Copper Ore"},
  {"name": "Sunda", "location": "S. Asia", "specialty": null},
  {"name": "Suva", "location": "Australia", "specialty": null},
  {"name": "Syracuse", "location": "Mediterranean", "specialty": null},
  {"name": "Tahiti", "location": "Australia", "specialty": null},
  {"name": "Tamatave", "location": "E. Africa", "specialty": null},
  {"name": "Ternate", "location": "S. Asia", "specialty": "Clove"},
  {"name": "Tiksi", "location": "Russia", "specialty": null},
  {"name": "Timbuktu", "location": "W. Africa", "specialty": "Ivory"},
  {"name": "Trebizond", "location": "Ottoman", "specialty": "Cotton Cloth"},
  {"name": "Tripoli", "location": "N. Africa", "specialty": null},
  {"name": "Tunis", "location": "N. Africa", "specialty": "Iron Ore"},
  {"name": "Valencia", "location": "Iberia", "specialty": "Wool Cloth"},
  {"name": "Valparaiso", "location": "S. America", "specialty": null},
  {"name": "Venice", "location": "Mediterranean", "specialty": "Glassware"},
  {"name": "Veracruz", "location": "C. America", "specialty": "Gold"},
  {"name": "Wanganui", "location": "Australia", "specialty": null},
  {"name": "Zeiton", "location": "E. Asia", "specialty": "Silk"}
];